uploads = []

[[generated]]
id = "XkQXXFOiNiCKRW_oPhT_-"
uri = "file://artifacts/mockup-sandbox/public/africa-map.png"
type = "image"
title = "Abstract tech map of Africa"

[[outputs]]
id = "8L_DG4yqlCL583PGu5k-H"
uri = "file://artifacts/iapay-pitch-video/public/audio/bg_music.mp3"
type = "audio"
title = "background music"

[[outputs]]
id = "nOg2-lFbb1RtxaQWcWMnV"
uri = "file://.local/outputs/Cobo-Africa-Payments.pptx"
type = "slides"
title = "Cobo Africa Payments.pptx"
